const money = (n, compact=false) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:compact?'compact':'standard',maximumFractionDigits:compact?1:0}).format(n);
const pct = n => `${n>=0?'+':''}${n.toFixed(1)}%`;
const css = n => getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const C={cyan:css('--cyan'),green:css('--green'),red:css('--red'),orange:css('--orange'),purple:css('--purple'),muted:css('--muted'),line:css('--line'),text:css('--text')};
let D, charts={}, tableLimit=12, sortState={key:'marketValue',dir:-1};

Chart.defaults.color=C.muted; Chart.defaults.borderColor='rgba(29,52,58,.65)'; Chart.defaults.font.family='DM Mono'; Chart.defaults.font.size=9;
const tooltip={backgroundColor:'#15272c',borderColor:C.line,borderWidth:1,titleColor:C.text,bodyColor:C.muted,padding:12,displayColors:true};
const baseScales={x:{grid:{display:false},ticks:{maxRotation:0}},y:{grid:{color:'rgba(29,52,58,.55)'},border:{display:false}}};

async function init(){
  try{D=await fetch('dashboard-data.json').then(r=>{if(!r.ok)throw Error(r.statusText);return r.json()});hydrate();buildCharts();bind();reveal();}
  catch(e){document.querySelector('main').innerHTML=`<section class="hero"><div><p class="eyebrow">DATA CONNECTION</p><h1>Dashboard data<br><span>couldn't load.</span></h1><p class="hero-copy">Run this site through a local web server, or regenerate dashboard-data.json. ${e.message}</p></div></section>`}
}
function hydrate(){const s=D.summary;
  document.querySelector('#asOf').textContent=`Data through ${new Date(D.sourceThrough+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}`;
  set('#heroReturn',pct(s.returnPct));set('#heroGain',`${money(s.netGain)} net gain`);set('#equity',money(s.equity));set('#fundingNote',`${money(s.funding)} contributed`);
  set('#realized',money(s.realized));set('#unrealized',money(s.unrealized));document.querySelector('#unrealized').classList.toggle('negative',s.unrealized<0);
  const give=Math.abs(s.unrealized/s.realized*100);set('#giveback',`${give.toFixed(0)}% of realized gains offset`);set('#winRate',`${s.winRate}%`);set('#dayRecord',`${s.winDays} green / ${s.lossDays} red days`);
  document.querySelector('#realizedMeter').style.width='100%';document.querySelector('#openMeter').style.width=`${Math.min(give,100)}%`;
  document.querySelector('#dayDots').innerHTML='<i></i>'.repeat(s.winDays)+'<i class="red"></i>'.repeat(s.lossDays);
  set('#focusHeadline',give>50?'Open losses are masking strong realized execution.':'Exposure is the clearest improvement lever.');
  set('#focusDetail',`${money(Math.abs(s.unrealized))} of open losses currently offsets ${give.toFixed(0)}% of realized profit. Review invalidation points before adding risk.`);
  set('#donutNet',money(s.realized+s.unrealized,true));set('#splitRealized',money(s.realized));set('#splitOpen',money(s.unrealized));set('#avgDay',`${money(s.avgWinDay)} avg green day`);
  set('#leverage',`${s.leverage.toFixed(2)}×`);set('#top5',`${s.top5Pct}%`);set('#positionCount',s.openPositions);set('#givebackPct',`${give.toFixed(0)}%`);
  set('#exposureText',`${money(s.exposure)} invested against ${money(s.equity)} estimated equity.`);set('#concentrationText',`Top 10 positions account for ${s.top10Pct}% of exposure.`);
  ring('#leverageRing',Math.min(s.leverage/2*100,100));ring('#concentrationRing',s.top5Pct);ring('#positionsRing',Math.min(s.openPositions/75*100,100));
  set('#methodology',D.methodology+' Raw brokerage details are not included in this public dataset.');renderTable();
}
function buildCharts(){
  const labels=D.series.map(x=>x.date),equity=D.series.map(x=>x.equity),funding=D.series.map(x=>x.funding);
  const ctx=document.querySelector('#sparkEquity').getContext('2d'),grad=ctx.createLinearGradient(0,0,0,60);grad.addColorStop(0,'rgba(87,230,211,.35)');grad.addColorStop(1,'rgba(87,230,211,0)');
  charts.spark=new Chart(ctx,{type:'line',data:{labels,datasets:[{data:equity,borderColor:C.cyan,backgroundColor:grad,fill:true,borderWidth:1.5,pointRadius:0,tension:.3}]},options:{responsive:true,plugins:{legend:{display:false},tooltip:{enabled:false}},scales:{x:{display:false},y:{display:false}},layout:{padding:0}}});
  charts.equity=new Chart(document.querySelector('#equityChart'),{type:'line',data:{labels,datasets:[{label:'Estimated equity',data:equity,borderColor:C.cyan,backgroundColor:'rgba(87,230,211,.07)',fill:true,borderWidth:2,pointRadius:0,tension:.25},{label:'Cumulative funding',data:funding,borderColor:'#426168',borderDash:[5,5],borderWidth:1.5,pointRadius:0,tension:0}]},options:{maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:false},tooltip:{...tooltip,callbacks:{label:c=>`${c.dataset.label}: ${money(c.raw)}`}}},scales:{...baseScales,y:{...baseScales.y,ticks:{callback:v=>money(v,true)}}}}});
  charts.composition=new Chart(document.querySelector('#compositionChart'),{type:'doughnut',data:{labels:['Realized profit','Open losses'],datasets:[{data:[Math.abs(D.summary.realized),Math.abs(D.summary.unrealized)],backgroundColor:[C.green,C.red],borderWidth:0,spacing:3}]},options:{cutout:'78%',plugins:{legend:{display:false},tooltip:{...tooltip,callbacks:{label:c=>`${c.label}: ${money(c.raw)}`}}}}});
  charts.daily=new Chart(document.querySelector('#dailyChart'),{type:'bar',data:{labels,data:D.series.map(x=>x.dailyRealized),datasets:[{data:D.series.map(x=>x.dailyRealized),backgroundColor:c=>c.raw>=0?'rgba(167,239,110,.8)':'rgba(255,107,107,.8)',borderRadius:2}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{...tooltip,callbacks:{label:c=>`Realized: ${money(c.raw)}`}}},scales:{...baseScales,y:{...baseScales.y,ticks:{callback:v=>money(v,true)}}}}});
  charts.monthly=new Chart(document.querySelector('#monthlyChart'),{type:'bar',data:{labels:D.monthly.map(x=>x.month),datasets:[{data:D.monthly.map(x=>x.realized),backgroundColor:[C.purple,C.cyan,C.green],borderRadius:3}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{...tooltip,callbacks:{label:c=>money(c.raw)}}},scales:{...baseScales,y:{...baseScales.y,ticks:{callback:v=>money(v,true)}}}}});
  const sym=[...D.symbols].sort((a,b)=>Math.abs(b.realized)-Math.abs(a.realized)).slice(0,16).sort((a,b)=>a.realized-b.realized);
  charts.symbol=new Chart(document.querySelector('#symbolChart'),{type:'bar',data:{labels:sym.map(x=>x.symbol),datasets:[{data:sym.map(x=>x.realized),backgroundColor:sym.map(x=>x.realized>=0?C.green:C.red),borderRadius:2}]},options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{...tooltip,callbacks:{label:c=>money(c.raw)}}},scales:{x:{...baseScales.y,ticks:{callback:v=>money(v,true)}},y:{grid:{display:false}}}}});
  const bubbles=D.positions.map((p,i)=>({x:p.marketValue,y:p.returnPct,r:Math.max(4,Math.min(24,Math.sqrt(Math.abs(p.marketValue))/3.3)),symbol:p.symbol,pnl:p.unrealized}));
  charts.risk=new Chart(document.querySelector('#riskMap'),{type:'bubble',data:{datasets:[{data:bubbles,backgroundColor:bubbles.map(x=>x.pnl>=0?'rgba(167,239,110,.65)':'rgba(255,107,107,.65)'),borderColor:bubbles.map(x=>x.pnl>=0?C.green:C.red),borderWidth:1}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{...tooltip,callbacks:{label:c=>`${c.raw.symbol} · ${money(c.raw.x)} · ${pct(c.raw.y)}`}}},scales:{x:{title:{display:true,text:'POSITION SIZE'},ticks:{callback:v=>money(v,true)},grid:{color:'rgba(29,52,58,.55)'}},y:{title:{display:true,text:'OPEN RETURN'},ticks:{callback:v=>`${v}%`},grid:{color:'rgba(29,52,58,.55)'}}}}});
  const top=D.positions.slice(0,9),other=D.positions.slice(9).reduce((a,x)=>a+x.marketValue,0);charts.allocation=new Chart(document.querySelector('#allocationChart'),{type:'doughnut',data:{labels:[...top.map(x=>x.symbol),'OTHER'],datasets:[{data:[...top.map(x=>x.marketValue),other],backgroundColor:[C.cyan,C.purple,C.orange,C.green,'#5e8b90','#6d6288','#8d775d','#527869','#40565d','#263b40'],borderColor:css('--panel'),borderWidth:3}]},options:{cutout:'62%',plugins:{legend:{position:'bottom',labels:{boxWidth:7,boxHeight:7,padding:13}},tooltip:{...tooltip,callbacks:{label:c=>`${c.label}: ${money(c.raw)}`}}}}});
}
function bind(){
  document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-range]').forEach(x=>x.classList.remove('active'));b.classList.add('active');range(b.dataset.range)});
  document.querySelector('#positionSearch').oninput=renderTable;document.querySelector('#showAll').onclick=()=>{tableLimit=999;renderTable()};
  document.querySelectorAll('th[data-sort]').forEach(th=>th.onclick=()=>{sortState.dir=sortState.key===th.dataset.sort?-sortState.dir:-1;sortState.key=th.dataset.sort;renderTable()});
  document.querySelector('#downloadSnapshot').onclick=downloadSnapshot;
  document.querySelectorAll('.info').forEach(el=>{el.onmouseenter=e=>showTip(e,el.dataset.tip);el.onmouseleave=hideTip});
}
function range(value){const n=value==='all'?D.series.length:+value,start=Math.max(0,D.series.length-n),slice=D.series.slice(start);['equity','daily'].forEach(k=>{charts[k].data.labels=slice.map(x=>x.date)});charts.equity.data.datasets[0].data=slice.map(x=>x.equity);charts.equity.data.datasets[1].data=slice.map(x=>x.funding);charts.daily.data.datasets[0].data=slice.map(x=>x.dailyRealized);charts.equity.update();charts.daily.update()}
function renderTable(){const q=document.querySelector('#positionSearch')?.value.toUpperCase()||'';let rows=D.positions.filter(x=>x.symbol.includes(q));rows.sort((a,b)=>typeof a[sortState.key]==='string'?a[sortState.key].localeCompare(b[sortState.key])*sortState.dir:(a[sortState.key]-b[sortState.key])*sortState.dir);document.querySelector('#positionRows').innerHTML=rows.slice(0,tableLimit).map(p=>`<tr><td>${p.symbol}</td><td>${money(p.marketValue)}</td><td class="${p.unrealized<0?'negative':'positive'}">${money(p.unrealized)}</td><td><span class="return-pill ${p.returnPct<0?'red':''}">${pct(p.returnPct)}</span></td><td><span class="price-pair">${money(p.avgCost)} / ${money(p.mark)}</span></td></tr>`).join('');document.querySelector('#showAll').style.display=rows.length>tableLimit?'block':'none'}
function downloadSnapshot(){const s=D.summary,text=`TRADING JOURNEY — ADVISOR SNAPSHOT\nData through ${D.sourceThrough}\n\nEstimated equity: ${money(s.equity)}\nContributions: ${money(s.funding)}\nEstimated net gain: ${money(s.netGain)} (${pct(s.returnPct)})\nRealized P&L: ${money(s.realized)}\nOpen P&L: ${money(s.unrealized)}\nGross exposure: ${money(s.exposure)} (${s.leverage}x equity)\nOpen positions: ${s.openPositions}\nTop 5 concentration: ${s.top5Pct}%\n\nMethodology: ${D.methodology}\n`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download=`trading-journey-${D.sourceThrough}.txt`;a.click();URL.revokeObjectURL(a.href)}
function reveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(x=>io.observe(x))}
function ring(sel,n){document.querySelector(sel).style.setProperty('--pct',n)}function set(sel,v){document.querySelector(sel).textContent=v}function showTip(e,t){const x=document.querySelector('#tooltip');x.textContent=t;x.style.display='block';x.style.left=`${e.clientX+12}px`;x.style.top=`${e.clientY+12}px`}function hideTip(){document.querySelector('#tooltip').style.display='none'}
init();
